version: '3'

services:
  postgress:
    container_name: postgress
    image: postgres:9.6.6-alpine
    volumes:
      - ./schema-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: myapp
      POSTGRES_DB: todos
    restart: on-failure
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    healthcheck:
      test: |
          apk add --no-cache sqlite
          sqlite3 /var/lib/pgadmin/pgadmin4.db 'INSERT OR IGNORE INTO server (id, user_id, servergroup_id, name, host, port, maintenance_db, username, password, ssl_mode, use_ssh_tunnel, tunnel_port, tunnel_authentication, connect_timeout) VALUES (10, 1, 1, "chatbot_prog_1", "postgres", 5432, "chatbot", "myapp", NULL, "prefer", 0, 22, 0, 0);' '.exit'
          exit 1
      interval: 0s
      timeout: 10s
      retries: 1
    depends_on:
      - postgress
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped