server:
  port: ${env.PORT:8080}
  servlet:
    context-path: /api/v1.0/
---
spring:
  flyway:
    locations: classpath:db/
    placeholder-prefix: $$
    schemas: todos
    table: flyway_schema_history
    baselineOnMigrate: true
  application:
    name: todos-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${cloud.services.postgresql.connection.username:myapp}
    url: ${cloud.services.postgresql.connection.jdbcurl:jdbc:postgresql://localhost:5432/todos}
    password: ${cloud.services.postgresql.connection.password:dbpass}
    platform: postgresql
    initialization-mode: always
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 20
      pool-name: HikariCP
---


spring:
  profiles:
    active: dev
  main: 
    allow-bean-definition-overriding: true
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
